[2023-06-14T02:31:38.164+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vamosSigue.llenar_tabla_from_file manual__2023-06-14T02:13:35.804016+00:00 [queued]>
[2023-06-14T02:31:38.181+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vamosSigue.llenar_tabla_from_file manual__2023-06-14T02:13:35.804016+00:00 [queued]>
[2023-06-14T02:31:38.182+0000] {taskinstance.py:1308} INFO - Starting attempt 5 of 5
[2023-06-14T02:31:38.204+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresFileOperator): llenar_tabla_from_file> on 2023-06-14 02:13:35.804016+00:00
[2023-06-14T02:31:38.211+0000] {standard_task_runner.py:57} INFO - Started process 126 to run task
[2023-06-14T02:31:38.215+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'vamosSigue', 'llenar_tabla_from_file', 'manual__2023-06-14T02:13:35.804016+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/dbeaverFunciona.py', '--cfg-path', '/tmp/tmpks15yrox']
[2023-06-14T02:31:38.217+0000] {standard_task_runner.py:85} INFO - Job 75: Subtask llenar_tabla_from_file
[2023-06-14T02:31:38.292+0000] {task_command.py:410} INFO - Running <TaskInstance: vamosSigue.llenar_tabla_from_file manual__2023-06-14T02:13:35.804016+00:00 [running]> on host b41452b45446
[2023-06-14T02:31:38.432+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='vamosSigue' AIRFLOW_CTX_TASK_ID='llenar_tabla_from_file' AIRFLOW_CTX_EXECUTION_DATE='2023-06-14T02:13:35.804016+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-14T02:13:35.804016+00:00'
[2023-06-14T02:31:38.433+0000] {postgres.py:158} INFO - Running copy expert: COPY datos FROM STDIN, filename: /opt/***/temp/file.tsv
[2023-06-14T02:31:38.451+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-06-14T02:31:38.510+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=vamosSigue, task_id=llenar_tabla_from_file, execution_date=20230614T021335, start_date=20230614T023138, end_date=20230614T023138
[2023-06-14T02:31:38.547+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-14T02:31:38.578+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
