[2023-06-13T03:26:09.892+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vamosSigue.populate_datos_table scheduled__2023-06-12T00:00:00+00:00 [queued]>
[2023-06-13T03:26:09.911+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vamosSigue.populate_datos_table scheduled__2023-06-12T00:00:00+00:00 [queued]>
[2023-06-13T03:26:09.911+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-13T03:26:09.934+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): populate_datos_table> on 2023-06-12 00:00:00+00:00
[2023-06-13T03:26:09.943+0000] {standard_task_runner.py:57} INFO - Started process 630 to run task
[2023-06-13T03:26:09.946+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'vamosSigue', 'populate_datos_table', 'scheduled__2023-06-12T00:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/dbeaverFunciona.py', '--cfg-path', '/tmp/tmp47mfts3x']
[2023-06-13T03:26:09.947+0000] {standard_task_runner.py:85} INFO - Job 48: Subtask populate_datos_table
[2023-06-13T03:26:10.022+0000] {task_command.py:410} INFO - Running <TaskInstance: vamosSigue.populate_datos_table scheduled__2023-06-12T00:00:00+00:00 [running]> on host a26553e1bb12
[2023-06-13T03:26:10.149+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='vamosSigue' AIRFLOW_CTX_TASK_ID='populate_datos_table' AIRFLOW_CTX_EXECUTION_DATE='2023-06-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-12T00:00:00+00:00'
[2023-06-13T03:26:10.151+0000] {sql.py:262} INFO - Executing: 
                INSERT INTO datos (id, country)
                VALUES ( 'us', 'estados unidos')
            
[2023-06-13T03:26:10.171+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-06-13T03:26:10.302+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-06-13T03:26:10.324+0000] {sql.py:375} INFO - Running statement: 
                INSERT INTO datos (id, country)
                VALUES ( 'us', 'estados unidos')
            , parameters: None
[2023-06-13T03:26:10.331+0000] {sql.py:384} INFO - Rows affected: 1
[2023-06-13T03:26:10.353+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=vamosSigue, task_id=populate_datos_table, execution_date=20230612T000000, start_date=20230613T032609, end_date=20230613T032610
[2023-06-13T03:26:10.400+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-13T03:26:10.445+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
